spring:
  couchbase:
    connection-string: wanglei1.macdao.com, wanglei2.macdao.com
    username: Administrator
    password: 111111
    bucketName: travel-sample
  boot:
    admin:
      client:
        url: http://localhost:8080
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'

