spring:
  couchbase:
    connection-string: 172.31.41.157,172.31.47.41,172.31.43.251
    username: Administrator
    password: 111111
    bucketName: travel-sample
  boot:
    admin:
      client:
        url: http://localhost:8080
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'

